"""Language pipeline: instructions -> semantic graph -> AST -> generated code."""

from __future__ import annotations

from dataclasses import dataclass

from .ir import Instruction, ProgramAST, SemanticEdge, SemanticGraph, SemanticNode

SUPPORTED_TARGETS = {"python", "c", "rust", "solidity", "kotlin"}


@dataclass(slots=True)
class PipelineResult:
    """Output artifacts of compilation pipeline."""

    instructions: list[Instruction]
    semantic_graph: SemanticGraph
    ast: ProgramAST
    code: str


def parse_instructions(source: str) -> list[Instruction]:
    """Parse source text into instruction objects.

    Syntax (line-based):
    - Lines separated by newlines.
    - Format: ACTION TARGET [| constraint1; constraint2]
    Example:
      generate rest_api | auth; pagination
    """
    instructions: list[Instruction] = []
    for raw_line in source.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        left, _, right = line.partition("|")
        parts = left.strip().split(maxsplit=1)
        if len(parts) != 2:
            raise ValueError(f"Invalid instruction line: {line!r}")

        action, target = parts
        constraints = [c.strip() for c in right.split(";") if c.strip()] if right else []
        instructions.append(
            Instruction(action=action.lower(), target=target, constraints=constraints)
        )

    if not instructions:
        raise ValueError("No valid instructions found in source.")
    return instructions


def build_semantic_graph(instructions: list[Instruction]) -> SemanticGraph:
    """Create semantic graph from instructions."""
    graph = SemanticGraph()
    graph.nodes.append(SemanticNode(id="program", kind="root", value="AIProgram"))

    for idx, instr in enumerate(instructions, start=1):
        node_id = f"instr_{idx}"
        graph.nodes.append(
            SemanticNode(
                id=node_id,
                kind="instruction",
                value=f"{instr.action}:{instr.target}",
            )
        )
        graph.edges.append(SemanticEdge(source="program", relation="contains", target=node_id))

        for c_idx, constraint in enumerate(instr.constraints, start=1):
            c_id = f"{node_id}_constraint_{c_idx}"
            graph.nodes.append(SemanticNode(id=c_id, kind="constraint", value=constraint))
            graph.edges.append(SemanticEdge(source=node_id, relation="constrained_by", target=c_id))

    return graph


def build_ast(instructions: list[Instruction]) -> ProgramAST:
    """Build AST from parsed instructions."""
    return ProgramAST(instructions=instructions)


def _generate_python(ast: ProgramAST) -> str:
    lines = [
        '"""Generated by ai-language-pro from AI Language instructions."""',
        "",
        "def run_program() -> list[str]:",
        "    steps: list[str] = []",
    ]
    for instr in ast.instructions:
        constraints = f" constraints={instr.constraints}" if instr.constraints else ""
        lines.append(
            f"    steps.append({instr.action!r} + ' ' + {instr.target!r} + {constraints!r})"
        )
    lines.extend(["    return steps", "", "if __name__ == '__main__':", "    print(run_program())"])
    return "\n".join(lines)


def _generate_c(ast: ProgramAST) -> str:
    lines = ["#include <stdio.h>", "", "int main(void) {"]
    for instr in ast.instructions:
        lines.append(f'    printf("{instr.action} {instr.target}\\n");')
    lines.append("    return 0;")
    lines.append("}")
    return "\n".join(lines)


def _generate_rust(ast: ProgramAST) -> str:
    lines = ["fn main() {"]
    for instr in ast.instructions:
        lines.append(f'    println!("{instr.action} {instr.target}");')
    lines.append("}")
    return "\n".join(lines)


def _generate_solidity(ast: ProgramAST) -> str:
    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.20;",
        "",
        "contract AIProgram {",
        "    function steps() external pure returns (string[] memory out) {",
        f"        out = new string[]({len(ast.instructions)});",
    ]
    for idx, instr in enumerate(ast.instructions):
        lines.append(f'        out[{idx}] = "{instr.action} {instr.target}";')
    lines.extend(["    }", "}"])
    return "\n".join(lines)


def _generate_kotlin(ast: ProgramAST) -> str:
    lines = ["fun main() {"]
    for instr in ast.instructions:
        lines.append(f'    println("{instr.action} {instr.target}")')
    lines.append("}")
    return "\n".join(lines)


def generate_code(ast: ProgramAST, target: str) -> str:
    """Generate code for a target language."""
    target_normalized = target.lower()
    if target_normalized not in SUPPORTED_TARGETS:
        raise ValueError(f"Unsupported target language: {target}")

    generators = {
        "python": _generate_python,
        "c": _generate_c,
        "rust": _generate_rust,
        "solidity": _generate_solidity,
        "kotlin": _generate_kotlin,
    }
    return generators[target_normalized](ast)


def compile_source(source: str, target: str = "python") -> PipelineResult:
    """Run complete pipeline and return artifacts."""
    instructions = parse_instructions(source)
    semantic_graph = build_semantic_graph(instructions)
    ast = build_ast(instructions)
    code = generate_code(ast, target=target)
    return PipelineResult(
        instructions=instructions,
        semantic_graph=semantic_graph,
        ast=ast,
        code=code,
    )
